### ISSUE TITLE
can’t open ‘/etc/cmh-ludl/openLuup_reload_for_docker’ No such file or directory

### ISSUE THREAD

**Issue by nodecentral** [vwout/docker-openluup#9]
Hi

I’m trying to do a fresh install of openLuup, and while it creates the required directories, it fails to load reporting the following error..
````
/bin/sh: can’t open ‘/etc/cmh-ludl/openLuup_reload_for_docker’ No such file or directory
````
Here is my Docker compose, not sure if the PUID/GUID are required but as this install is on a old QNAP NAS, where I also have a number of linuxserver containers running, as they seem to use that, I’ve applied it here for consistency..
````
version: '2.3'

services:
    openluup:
        image: vwout/openluup:alpine
        container_name: openluup
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /share/Container/openluup:/etc/cmh-ludl
        ports:
            - "3480:3480"
 ````
The cmh-ludl folder that is created does not have any files in only a logs and backup folder.

I’m assuming this is a JSON it’s looking for, but where would I get that from, if one is not initially created automatically if an existing one is not present ?
